#!/usr/bin/perl -w
use strict;
use Cwd;
use Data::Dumper;
use Getopt::Long;
use Try::Tiny;

### This is a sub script for CCseqBasic triplicate analysis which generates union bedgraphs for all oligos from 3 test and 3 control samples

### (C) Damien Downes 16th May 2018.


&GetOptions
(
    "dir=s"=> \my @dirs,                # -dir          The directories that contain the gff files for all the samples (subdirectories) that you want to analyse,
                                        #               separated by only a comma (no space); these subdirectories need to contain the gff files, so it will be the ‘F6’
                                        #               folder generated by CC4; you don’t have to give the full path to these folders, just direct down from the path
                                        #               you’ve entered (it will be two directories down)
    "viewpoints=s" => \my $vp_file,     # -viewpoints   VIEWPOINT	CHR VP_START VP_STOP EXCLSTART EXCLSTOP REGIONSTART REGIONSTOP BINSIZE WINDOWSIZE
                                        #               Note: chr is numeric  (1 NOT chr1)
    "samples=s"=> \ my $samples,	# -samples	Sample1,Sample2,Sample3
);


my ($sampleA, $sampleB, $sampleC, $sampleD, $sampleE, $sampleF) = split /\,/, $samples;
 
my $s1_r1;
my $s1_r2;
my $s1_r3;
my $s2_r1;
my $s2_r2;
my $s2_r3;
my $s3_r1;
my $s3_r2;
my $s3_r3;
my $s4_r1;
my $s4_r2;
my $s4_r3;
my $s5_r1;
my $s5_r2;
my $s5_r3;
my $s6_r1;
my $s6_r2;



($s1_r1,$s1_r2,$s1_r3,$s2_r1,$s2_r2,$s2_r3,$s3_r1,$s3_r2,$s3_r3,$s4_r1,$s4_r2,$s4_r3,$s5_r1,$s5_r2,$s5_r3,$s6_r1,$s6_r2) = split(/,/,join(',',@dirs));

my $sample_file = "Sample_order.txt";

open(LIST, ">$sample_file") or die "Can't open $sample_file file";
print LIST "Sample_1:\t$sampleA\n";
print LIST "Sample_1_reps:\t$s1_r1\t$s1_r2\t$s1_r3\n";
print LIST "Sample_2:\t$sampleB\n";
print LIST "Sample_2_reps:\t$s2_r1\t$s2_r2\t$s2_r3\n";
print LIST "Sample_3:\t$sampleC\n";
print LIST "Sample_3_reps:\t$s3_r1\t$s3_r2\t$s3_r3\n";
print LIST "Sample_4:\t$sampleD\n";
print LIST "Sample_4_reps:\t$s4_r1\t$s4_r2\t$s4_r3\n";
print LIST "Sample_5:\t$sampleE\n";
print LIST "Sample_5_reps:\t$s5_r1\t$s5_r2\t$s5_r3\n";
print LIST "Sample_6:\t$sampleF\n";
print LIST "Sample_6_reps:\t$s6_r1\t$s6_r2\n";

my $bedtools_command = "bedtools_commands_TEMP.txt";
open(BED, ">$bedtools_command") or die "Can't open $bedtools_command file";
open(VP, $vp_file) or die "Can't open $vp_file file";
while (my $target = <VP>)
        { 
        chomp $target;
        my ($vp, @rest) = split(' ', $target);
              
        my $file1 = "$s1_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file2 = "$s1_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file3 = "$s1_r3\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file4 = "$s2_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file5 = "$s2_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file6 = "$s2_r3\_$vp\_cis_normalised_sorted_TEMP.bedgraph";      
        my $file7 = "$s3_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file8 = "$s3_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file9 = "$s3_r3\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file10 = "$s4_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file11 = "$s4_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file12 = "$s4_r3\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file13 = "$s5_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file14 = "$s5_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file15 = "$s5_r3\_$vp\_cis_normalised_sorted_TEMP.bedgraph";
        my $file16 = "$s6_r1\_$vp\_cis_normalised_sorted_TEMP.bedgraph";      
        my $file17 = "$s6_r2\_$vp\_cis_normalised_sorted_TEMP.bedgraph";       
        
        print BED "bedtools unionbedg -i $file1 $file2 $file3 $file4 $file5 $file6 $file7 $file8 $file9 $file10 $file11 $file12 $file13 $file14 $file15 $file16 $file17 > $vp\_normalised.unionbdg\n";

        $file1 = "$s1_r1\_$vp\_sorted_TEMP_raw.bedgraph";
        $file2 = "$s1_r2\_$vp\_sorted_TEMP_raw.bedgraph";
        $file3 = "$s1_r3\_$vp\_sorted_TEMP_raw.bedgraph";
        $file4 = "$s2_r1\_$vp\_sorted_TEMP_raw.bedgraph";
        $file5 = "$s2_r2\_$vp\_sorted_TEMP_raw.bedgraph";
        $file6 = "$s2_r3\_$vp\_sorted_TEMP_raw.bedgraph";
        $file7 = "$s3_r1\_$vp\_sorted_TEMP_raw.bedgraph";
        $file8 = "$s3_r2\_$vp\_sorted_TEMP_raw.bedgraph";
        $file9 = "$s3_r3\_$vp\_sorted_TEMP_raw.bedgraph";
        $file10 = "$s4_r1\_$vp\_sorted_TEMP_raw.bedgraph";
        $file11 = "$s4_r2\_$vp\_sorted_TEMP_raw.bedgraph";
        $file12 = "$s4_r3\_$vp\_sorted_TEMP_raw.bedgraph";
        $file13 = "$s5_r1\_$vp\_sorted_TEMP_raw.bedgraph";
        $file14 = "$s5_r2\_$vp\_sorted_TEMP_raw.bedgraph";
        $file15 = "$s5_r3\_$vp\_sorted_TEMP_raw.bedgraph";
        $file16 = "$s6_r1\_$vp\_sorted_TEMP_raw.bedgraph";      
        $file17 = "$s6_r2\_$vp\_sorted_TEMP_raw.bedgraph";          
        
        print BED "bedtools unionbedg -i $file1 $file2 $file3 $file4 $file5 $file6 $file7 $file8 $file9 $file10 $file11 $file12 $file13 $file14 $file15 $file16 $file17  -header -names $s1_r1 $s1_r2 $s1_r3 $s2_r1 $s2_r2 $s2_r3 $s3_r1 $s3_r2 $s3_r3 $s4_r1 $s4_r2 $s4_r3 $s5_r1 $s5_r2 $s5_r3 $s6_r1 $s6_r2 > $vp\_raw.unionbdg\n";

        }

close VP;
close BED;

exit;