#!/bin/bash
#$ -cwd
#$ -M ddownes
#$ -m eas
#$ -j n
#$ -N ENCODE


wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwA549Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAg04449Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAg04450Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAg09309Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAg09319Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAg10803Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwAoafSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwBe2cSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwBjSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwBonemarrowmscSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwCaco2Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwCd20ro01778Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwGm04503Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwGm04504Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwGm06990Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwGm12865Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwGm12878Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwH7hescDiffprota5dSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwH7hescDiffprota14dSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwH7hescSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHacSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHaepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHahSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHaspSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHbmecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHbvsmcSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHcfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHcfaaSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHcmSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHconfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHcpepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHct116Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHeepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHelas3Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHepg2Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHffSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHffmycSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHgfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHipepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHl60Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdadSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdbladSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdblneoSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdlyadSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdlyneoSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecdneoSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmveclblSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHmvecllySignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHnpcepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHpafSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHpdlfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHpfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHrcepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHreSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHrgecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHrpepicSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHsmmSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHsmmtubeSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHuvecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwHvmfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwJurkatSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwK562Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwLhcnm2Diff4dSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwLhcnm2Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwLncapSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwM059jSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwMcf7Estradiol100nm1hrSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwMcf7Estradiolctrl0hrSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwMcf7Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwMonocytescd14ro01746Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNb4Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhaSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhberaSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhdfadSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhdfneoSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhekSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNhlfSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwNt2d1Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwPanc1Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwPrecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwRpmi7951Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwRptecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwSaecSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwSkmcSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwSknmcSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwSknshraSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwT47dSignal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwTh1Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwTh1wb54553204Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwTh2Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwWerirb1Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwWi38Signal.bw
wget http://hgdownload.cse.ucsc.edu/gbdb/hg38/bbi/wgEncodeRegDnase/wgEncodeRegDnaseUwWi384ohtam20nm72hrSignal.bw
